### PR TITLE
use version numbers instead of release in .travis.yml

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
https://stackoverflow.com/questions/2698269/how-do-you-change-library-location-in-r said setting an `R_LIBS` environment variable might help, but I guess not. Not great to have a package that can't be installed non-interactively. Is there no default way of saying "install in a user-writable location" without having to go to annoying lengths?

**Comment by pkofod** [comment]
> https://stackoverflow.com/questions/2698269/how-do-you-change-library-location-in-r said setting an R_LIBS environment variable might help, but I guess not. Not great to have a package that can't be installed non-interactively. Is there no default way of saying "install in a user-writable location" without having to go to annoying lengths?

Thanks for trying to help out, but I really don't think it's worth it for you to spend too much time on it. I've tried searching and asking people about it (I'm not an R person myself, I just found this small part of statmod convenient for something I often do), and it seems that packages weren't really meant to be installed from scripts like this.

Usually I just use RCall directly, but I have a blog-post using this (waiting for me to find out how to get this working) so I thought I would put it in a small wrapper package. In the future I would prefer to simply re-write it in Julia. I get why this would be sorted out before you'd be comfortable including it in METADATA.jl, so maybe it's just better for me to tell people to `Pkg.clone`, and then I can publish it in METADATA.jl once the node and weights are the output of actual Julia code.

Once again, sorry for the noise.

**Comment by tkelman** [comment]
ok. at least the first commit here is relevant.

**Comment by pkofod** [comment]
thanks. I changed it to use a julia quadrature provider, so it's all good now :)

**Pull request closed without merging**
